// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOru9r3ww5UoDBSKtPQJUMTK72vhlQ6JI',
    appId: '1:1044671739234:web:764696a60dfc0534f4683b',
    messagingSenderId: '1044671739234',
    projectId: 'truck-dispatch-system',
    authDomain: 'truck-dispatch-system.firebaseapp.com',
    storageBucket: 'truck-dispatch-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBExJKXOrzGqcTuh0Ic5mROpb-oP3d83rw',
    appId: '1:1044671739234:android:3ecb4c9fe04064f3f4683b',
    messagingSenderId: '1044671739234',
    projectId: 'truck-dispatch-system',
    storageBucket: 'truck-dispatch-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBipyGvuN1yj4gO-HNqiUNtyBtqTSxgEHc',
    appId: '1:1044671739234:ios:15b3c55ede75baeaf4683b',
    messagingSenderId: '1044671739234',
    projectId: 'truck-dispatch-system',
    storageBucket: 'truck-dispatch-system.firebasestorage.app',
    iosBundleId: 'com.example.lojistik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBipyGvuN1yj4gO-HNqiUNtyBtqTSxgEHc',
    appId: '1:1044671739234:ios:15b3c55ede75baeaf4683b',
    messagingSenderId: '1044671739234',
    projectId: 'truck-dispatch-system',
    storageBucket: 'truck-dispatch-system.firebasestorage.app',
    iosBundleId: 'com.example.lojistik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOru9r3ww5UoDBSKtPQJUMTK72vhlQ6JI',
    appId: '1:1044671739234:web:5fc5e0973dcc951bf4683b',
    messagingSenderId: '1044671739234',
    projectId: 'truck-dispatch-system',
    authDomain: 'truck-dispatch-system.firebaseapp.com',
    storageBucket: 'truck-dispatch-system.firebasestorage.app',
  );
}
